export const mockData = [
  {
    id: "728ed52f",
    amount: 100,
    status: "pending",
    email: "m@example.com",
    product: "Product A",
    date: "2024-12-01",
    insights: {
      customerSegment: "Individual",
      churnRisk: "Low",
      upsellPotential: "Medium",
    },
  },
  {
    id: "a123bc45",
    amount: 250,
    status: "success",
    email: "j@example.com",
    product: "Product B",
    date: "2024-12-02",
    insights: {
      customerSegment: "Small Business",
      churnRisk: "Medium",
      upsellPotential: "High",
    },
  },
  {
    id: "3c56ef78",
    amount: 75,
    status: "processing",
    email: "k@example.com",
    product: "Product C",
    date: "2024-12-03",
    insights: {
      customerSegment: "Enterprise",
      churnRisk: "High",
      upsellPotential: "Low",
    },
  },
  {
    id: "4d89gh90",
    amount: 500,
    status: "failed",
    email: "l@example.com",
    product: "Product D",
    date: "2024-12-04",
    insights: {
      customerSegment: "Individual",
      churnRisk: "Low",
      upsellPotential: "High",
    },
  },
  {
    id: "5e12ij34",
    amount: 1200,
    status: "success",
    email: "n@example.com",
    product: "Product E",
    date: "2024-12-05",
    insights: {
      customerSegment: "Small Business",
      churnRisk: "Medium",
      upsellPotential: "High",
    },
  },
  {
    id: "6f34kl56",
    amount: 450,
    status: "processing",
    email: "o@example.com",
    product: "Product F",
    date: "2024-12-06",
    insights: {
      customerSegment: "Individual",
      churnRisk: "High",
      upsellPotential: "Medium",
    },
  },
  {
    id: "7g56mn78",
    amount: 30,
    status: "pending",
    email: "p@example.com",
    product: "Product G",
    date: "2024-12-07",
    insights: {
      customerSegment: "Small Business",
      churnRisk: "Low",
      upsellPotential: "Low",
    },
  },
  {
    id: "8h78op90",
    amount: 800,
    status: "success",
    email: "q@example.com",
    product: "Product H",
    date: "2024-12-08",
    insights: {
      customerSegment: "Enterprise",
      churnRisk: "Medium",
      upsellPotential: "High",
    },
  },
  {
    id: "9i90qr12",
    amount: 150,
    status: "failed",
    email: "r@example.com",
    product: "Product I",
    date: "2024-12-09",
    insights: {
      customerSegment: "Individual",
      churnRisk: "High",
      upsellPotential: "Low",
    },
  },
  {
    id: "0j12st34",
    amount: 600,
    status: "processing",
    email: "s@example.com",
    product: "Product J",
    date: "2024-12-10",
    insights: {
      customerSegment: "Small Business",
      churnRisk: "Low",
      upsellPotential: "Medium",
    },
  },
];
